language: node_js
node_js:
- '8'
branches:
  only:
  - develop
  - master
cache: yarn
install: ci/install.sh
script: ci/script.sh
deploy:
  provider: heroku
  api_key:
    secure: rBzw+iTg7Cy0vdF01HL9KAQjYmwDPWqNjDAIiXNxS3d7t4vGGbcu+TKF+IAfRtDlg/FGflwdQ8cYCJzhH3M9wij99gFiyJD6B6IVtgH523IxsXRlXIEM+stJKvTJeyDZgIDxT0CErjUxYN0mMdKRYqFTdwAR5l7wxZK/Z5LF/i6bDj2hnZKfqFbZqtdOEtuzUY9HkqWUM3KQ5WZJYHyVIikx9e2uP+Qnu1EiV9x45SZS8rZpCwFB4L4F6vZjcHS3epK4xXe1UaNHmIbrCdF2sspKKCV8LwzwK6VlnFa91Y9BPTbzdYOYIcLp/E8AVrQ2w8C7KQ51Qel9/NdM6UXDSdVoXv669Xc9vaOj44Irp3Aev2fOJAPRFkL7pk++2uaQsI6NlOAl48yxNFiWHgRv15HwLAb6fGft0EMbo2ULkEL//sJOgoe6sYsr6lwZgJ5fORIwTNeMHDv7VAgyiTiaQ0IDaS5yoKO60+7P4ziBzdvrC4zFxwpaDZv2SizlT/EkynAQIroGNgDgWa/MdbzMFu/dVbMktEyVAKrqrRYZfKDboOGjdn/7ojVs5lCYgoL9VxuTa6FJ2HfdQxZuYWYFgND2S2FzFCO8+GNYwfrZbWM32Zz1wOzv7i0eKrky2b2/xVzDhO4noJP5FTFyagd+egQblIjlBcgSXfNlByGHVeg=
  app: amnesty-api
  run: "yarn db:migrate"
